name: Update README2

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
     contents: write
     
    steps:
    
      - uses: actions/checkout@v2.3.4
     
      - uses: Jsebashr/github-activity-readme@master
     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

